plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-engines.cjs
    spec: 'https://raw.githubusercontent.com/devoto13/yarn-plugin-engines/main/bundles/%40yarnpkg/plugin-engines.js'
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'

supportedArchitectures:
  cpu:
    - x64
    - arm64
  os:
    - linux
    - darwin

yarnPath: .yarn/releases/yarn-3.1.1.cjs

packageExtensions:
  redux-mock-store@*:
    peerDependencies:
      redux: '*'
  react-intl@*:
    dependencies:
      '@formatjs/ecma402-abstract': '1.9.7'
  '@formatjs/intl@*':
    dependencies:
      '@formatjs/icu-messageformat-parser': '2.0.10'
  react-grid-layout@*:
    peerDependencies:
      react: '*'
      react-dom: '*'
  eslint-module-utils@*:
    dependencies:
      eslint-import-resolver-node: '*'
