packageExtensions:
  "@formatjs/intl@*":
    dependencies:
      "@formatjs/icu-messageformat-parser": 2.0.10
  eslint-module-utils@*:
    dependencies:
      eslint-import-resolver-node: "*"
  react-ga@*:
    dependencies:
      prop-types: ^15.6.0
  react-intl@*:
    dependencies:
      "@formatjs/ecma402-abstract": 1.9.7
  redux-mock-store@*:
    peerDependencies:
      redux: "*"
  swagger-ui-react@*:
    dependencies:
      autolinker: "*"
      btoa: "*"
      cookie: "*"
      deepmerge: "*"
      fast-json-patch: "*"
      formdata-node: "*"
      is-plain-object: "*"
      isarray: "*"
      qs: "*"
      regenerator-runtime: "*"
      traverse: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-engines.cjs
    spec: "https://raw.githubusercontent.com/devoto13/yarn-plugin-engines/main/bundles/%40yarnpkg/plugin-engines.js"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"

supportedArchitectures:
  cpu:
    - x64
    - arm64
  os:
    - linux
    - darwin

yarnPath: .yarn/releases/yarn-3.2.3.cjs
