import { createGlobalTheme, createTheme } from '@vanilla-extract/css';
import * as colors from './colors';

export const zIndexVars = createGlobalTheme(':root', {
  modal: '10001',
  modalInner: '10002',
});

export const sizeVars = createGlobalTheme(':root', {
  auto: 'auto' as const,
  full: '100%' as const,
  '0': '0px' as const,
  // '0.5x': '2px' as const,
  '1x': '4px' as const,
  '1.5x': '6px' as const,
  '2x': '8px' as const,
  '3x': '12px' as const,
  '4x': '16px' as const,
  '5x': '20px' as const,
  '6x': '24px' as const,
  '7x': '28px' as const,
  '8x': '32px' as const,
  '9x': '36px' as const,
  '10x': '40px' as const,
  // '11x': '44px' as const,
  // '12x': '48px' as const,
  '13x': '52px' as const,
  '14x': '56px' as const,
  // '15x': '60px' as const,
  // '16x': '64px' as const,
  // '17x': '68px' as const,
  '18x': '72px' as const,
  // '19x': '76px' as const,
  '20x': '80px' as const,
});

export const radiiVars = createGlobalTheme(':root', {
  '0': '0px' as const,
  '1x': '4px' as const,
  '2x': '8px' as const,
  circle: '9999px' as const,
});

export const transitionDurationVars = createGlobalTheme(':root', {
  base: '0.3s',
});

export const [themeLight, vars] = createTheme({
  boxShadows: {
    dropdown: `8px 8px 10px ${colors.black10}`,
    modal: `8px 4px 14px ${colors.black10}`,
    btnPrimaryFocus: `0 7px 11px ${colors.mystic90}`,
    btnSecondaryFocus: `0 7px 11px ${colors.shark19}`,
  },
  colors: {
    transparent: colors.transparent,

    beta: colors.goldTips,
    primary: colors.hawkesBlue,
    danger: colors.burntSienna,
    success: colors.oceanGreen,
    text: colors.mineShaft,
    textHighlighted: colors.goldTips,
    textMuted: colors.mineShaft50,
    interactive: colors.luckyPoint,
    interactiveHighlighted: colors.luckyPointLighter,
    alert: colors.flamingo,
    dropdown: colors.white,
    dropdownBorder: colors.selago,
    dropdownItem: colors.transparent,
    dropdownItemHover: colors.hawkesBlue,
    dropdownItemBorderBottom: colors.whiteLilac,
    dropdownItemActiveBefore: colors.cornflowerBlue,
    dropdownItemText: colors.silverChalice,
    dropdownItemHoverText: colors.black,
    dropdownItemActiveText: colors.black,
    dropdownItemIcon: colors.cornflowerBlue,
    dropdownItemHoverIcon: colors.indigo,
    dropdownItemActiveIcon: colors.indigo,
    btnPrimaryBg: colors.goldTips,
    btnPrimaryBgHover: colors.lightningYellow,
    btnPrimaryBgActive: colors.galliano,
    btnPrimaryBgDisabled: colors.mystic,
    btnPrimaryText: colors.catskillWhite,
    btnPrimaryTextDisabled: colors.manatee,
    btnSecondaryBg: colors.indigo,
    btnSecondaryBgHover: colors.indigoLight,
    btnSecondaryBgActive: colors.governorBay,
    btnSecondaryBgDisabled: colors.mystic,
    btnSecondaryText: colors.catskillWhite,
    btnSecondaryTextDisabled: colors.manatee,
    btnDangerBg: colors.burntSienna,
    btnDangerBgHover: colors.salmon,
    btnDangerBgActive: colors.flamingo,
    btnDangerBgDisabled: colors.mystic,
    btnDangerText: colors.catskillWhite,
    btnDangerTextDisabled: colors.manatee,
    themeSwitcherBorder: colors.selago,
    themeSwitcherBorderHover: colors.luckyPoint,
    themeSwitcherSun: colors.white,
    themeSwitcherSunHover: colors.white,
    themeSwitcherMoon: colors.luckyPoint,
    spinner01: colors.black20,
    spinner02: colors.black,
    backdrop: colors.black30,

    footerBg: colors.luckyPoint,
    footerTitle: colors.spindle,
    footerBorder: colors.sapphire,
    footerColor: colors.spindle,
    footerLinkColor: colors.cornflowerBlue,
    footerLinkColorHover: colors.goldTips,
    footerSocialIcon: colors.indigo,
    footerSocialIconHover: colors.spindle,

    infoBg: colors.whiteLilac,
    statBg: colors.whiteLilac,
    statIcon: colors.indigo30,

    modal: colors.white,
    modalHeaderBorderBottom: colors.mako10,

    skeleton: colors.black10,
    skeletonHighlighted: colors.silver,

    switcherTrack: colors.mako10,
    switcherTrackShadow: colors.mako10,
    switcherTrackChecked: colors.goldTips25,
    switcherTrackShadowChecked: colors.goldTips10,
    switcherThumb: colors.mako80,
    switcherThumbChecked: colors.goldTips,

    radio: colors.mako,
    radioShadow: colors.mako10,
    radioChecked: colors.goldTips,
    radioShadowChecked: colors.goldTips10,
  },
});

export const themeDark = createTheme(vars, {
  boxShadows: {
    dropdown: `8px 8px 10px ${colors.black10}`,
    modal: `8px 4px 14px ${colors.black10}`,
    btnPrimaryFocus: `0 7px 11px ${colors.mystic15}`,
    btnSecondaryFocus: `0 7px 11px ${colors.mystic15}`,
  },
  colors: {
    transparent: colors.transparent,

    beta: colors.goldTips,
    primary: colors.mako,
    danger: colors.burntSienna,
    success: colors.oceanGreen,
    text: colors.whiteLilac,
    textHighlighted: colors.goldTips,
    textMuted: colors.whiteLilac50,
    interactive: colors.silverChalice,
    interactiveHighlighted: colors.gray,
    alert: colors.flamingo,
    dropdown: colors.ebonyClay,
    dropdownBorder: colors.transparent,
    dropdownItem: colors.transparent,
    dropdownItemHover: colors.mako,
    dropdownItemBorderBottom: colors.bunker,
    dropdownItemActiveBefore: colors.indigo,
    dropdownItemText: colors.silverChalice,
    dropdownItemHoverText: colors.white,
    dropdownItemActiveText: colors.spindle,
    dropdownItemIcon: colors.doveGray,
    dropdownItemHoverIcon: colors.white,
    dropdownItemActiveIcon: colors.spindle,
    btnPrimaryBg: colors.goldTips,
    btnPrimaryBgHover: colors.saffron,
    btnPrimaryBgActive: colors.goldenGrass,
    btnPrimaryBgDisabled: colors.mystic,
    btnPrimaryText: colors.catskillWhite,
    btnPrimaryTextDisabled: colors.manatee,
    btnSecondaryBg: colors.cornflowerBlueLighter,
    btnSecondaryBgHover: colors.anakiwa,
    btnSecondaryBgActive: colors.cornflowerBlueDarken,
    btnSecondaryBgDisabled: colors.mystic,
    btnSecondaryText: colors.catskillWhite,
    btnSecondaryTextDisabled: colors.manatee,
    btnDangerBg: colors.burntSienna,
    btnDangerBgHover: colors.salmon,
    btnDangerBgActive: colors.flamingo,
    btnDangerBgDisabled: colors.mystic,
    btnDangerText: colors.catskillWhite,
    btnDangerTextDisabled: colors.manatee,
    themeSwitcherBorder: colors.abbey,
    themeSwitcherBorderHover: colors.silverChalice,
    themeSwitcherSun: colors.silver,
    themeSwitcherSunHover: colors.mercury,
    themeSwitcherMoon: colors.abbey,
    spinner01: colors.white20,
    spinner02: colors.white,
    backdrop: colors.black30,

    footerBg: colors.ebonyClay,
    footerTitle: colors.silverChalice,
    footerBorder: colors.tuna,
    footerColor: colors.doveGray,
    footerLinkColor: colors.doveGray,
    footerLinkColorHover: colors.goldTips,
    footerSocialIcon: colors.doveGray,
    footerSocialIconHover: colors.silverChalice,

    infoBg: colors.mako,
    statBg: colors.mako,
    statIcon: colors.white30,

    modal: colors.charade,
    modalHeaderBorderBottom: colors.white10,

    skeleton: colors.black10,
    skeletonHighlighted: colors.white30,

    switcherTrack: colors.white10,
    switcherTrackShadow: colors.white10,
    switcherTrackChecked: colors.goldTips25,
    switcherTrackShadowChecked: colors.goldTips10,
    switcherThumb: colors.white80,
    switcherThumbChecked: colors.goldTips,

    radio: colors.white,
    radioShadow: colors.white10,
    radioChecked: colors.goldTips,
    radioShadowChecked: colors.goldTips10,
  },
});
